### ISSUE TITLE
Decoding Eddystone URL

### ISSUE THREAD

**Issue by spriggsy** [theBASTI0N/ble2mqtt#8]
Hi, thanks for your great lib.

Its working really well on my Pi zero
Im using it to decode self programmed NRF51822 beacons for my home assistant.

Its working great if I program them as Eddystone UUID's but If I use Eddystone URL only the .com is decoded, it misses out all the http://example part

would be great if you could point me in the right direction

many thanks
Spriggsy

**Comment by ghost** [comment]
Try updating the decoder:

`pip3 install beacondecoder --upgrade`

https://pypi.org/project/beacondecoder/

If that doesn't fix the issue could you paste an example of the packet being sent by the tag. You can modify the url slighlty if needed.

**Comment by spriggsy** [comment]
Hi thanks for looking into this

It stated that Im already using the latest update.

the raw packet being sent is:
0x0201060302AAFE0E16AAFE10EE006578616D706C6507

and the url decodes a https://www.example.com

Hope this info helps a bit?

**Comment by ghost** [comment]
Hey Thanks for that.

If you run:
`pip3 install beacondecoder --upgrade`

There is a new version v0.7.7

That should fix the issue.

**Comment by ghost** [comment]
@spriggsy If you are still having this issue you can create a new issue.

This issue should now be fixed.
